Jb\SimpleForumBundle\Entity\ForumCategory:
    type: entity
    table: simpleforum_category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            notnull: true
            length: 255
        parentId:
            type: integer
            nullable: true
            column: parent_id
        pathString:
            type: string
            length: 255
            nullable: true
            column: path_string
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    manyToOne:
        parent:
            targetEntity: ForumCategory
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: CASCADE
    oneToMany:
        children:
            targetEntity: ForumCategory
            mappedBy: parent
    lifecycleCallbacks:
        prePersist: [ updateDate ]
        postPersist: [  ]
