Jb\SimpleForumBundle\Entity\Topic:
    type: entity
    table: simpleforum_topic
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            nullabble: false
            length: 255
        categoryId:
            type: integer
            nullable: true
            column: category_id
        content:
            type: text
            nullabble: true
        slug:
            type: string
            length: 255
            nullable: false
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: topics
            joinColumn:
                name: category_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks:
        prePersist: [ updateDate ]
        postPersist: [  ]
